Repository FromDoppler/doppler-clover-api, pull requests merged in 2023-08, with the labels that each got.

#38 [DAT-1634] - Update refund endpoint
  Doppler.CloverAPI.Test/Controllers/PaymentControlleTest.cs
  Doppler.CloverAPI/Controllers/PaymentController.cs
  Doppler.CloverAPI/Requests/RefundRequest.cs
  Doppler.CloverAPI/Services/CloverService.cs
  Doppler.CloverAPI/Services/ICloverService.cs
Labels: size/M

#48 [DAT-1674] - validate credit card before create charge
  Doppler.CloverAPI/Services/CloverService.cs
Labels: size/XS

#47 Dat 1662 - Add new clover requirement
  .editorconfig
  Doppler.CloverAPI.Test/AuthorizationTest.cs
  Doppler.CloverAPI.Test/Controllers/PaymentControlleTest.cs
  Doppler.CloverAPI.Test/Services/ClientAddressServiceTest.cs
  Doppler.CloverAPI/Controllers/CustomerController.cs
  Doppler.CloverAPI/Controllers/PaymentController.cs
  Doppler.CloverAPI/Doppler.CloverAPI.csproj
  Doppler.CloverAPI/Extensions/HttpRequestHeadersExtension.cs
  Doppler.CloverAPI/Infrastructure/DatabaseConnectionFactory.cs
  Doppler.CloverAPI/Infrastructure/DopplerDatabaseSettings.cs
  Doppler.CloverAPI/Infrastructure/IDatabaseConnectionFactory.cs
  Doppler.CloverAPI/Infrastructure/IUserRepository.cs
  Doppler.CloverAPI/Infrastructure/UserRepository.cs
  Doppler.CloverAPI/Middleware/RequestLoggingMiddleware.cs
  Doppler.CloverAPI/Services/ClientAddressService.cs
  Doppler.CloverAPI/Services/CloverService.cs
  Doppler.CloverAPI/Services/IClientAddressService.cs
  Doppler.CloverAPI/Services/ICloverService.cs
  Doppler.CloverAPI/Startup.cs
  Doppler.CloverAPI/appsettings.Development.json
  Doppler.CloverAPI/appsettings.int.json
  Doppler.CloverAPI/appsettings.json
  Doppler.CloverAPI/appsettings.qa.json
Labels: size/L
